"""add advisor_name and advisor_email to documents

Revision ID: 26a3e83bbb04
Revises: 3807eb3928dc
Create Date: 2025-12-01 21:26:30.958661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a3e83bbb04'
down_revision: Union[str, Sequence[str], None] = '3807eb3928dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('advisor_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('advisor_email', sa.String(), nullable=True))
    op.alter_column('documents', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'advisor_email')
    op.drop_column('documents', 'advisor_name')
    # ### end Alembic commands ###
